Repository IGNF/road2, pull requests merged in 2023-03, with the labels that each got.

#42 fix(docker): limit conan version for valhalla build
  docker/distributions/debian/Dockerfile
Labels: bug

#39 Development of health route
  changelog.md
  docker/dev/docker-compose.yml
  documentation/test/integration/readme.md
  src/js/administrator/administrator.js
  src/js/apis/admin/1.0.0/controller/controller.js
  src/js/apis/admin/1.0.0/index.js
  src/js/requests/healthRequest.js
  src/js/requests/isochroneRequest.js
  src/js/requests/nearestRequest.js
  src/js/requests/request.js
  src/js/requests/routeRequest.js
  src/js/responses/healthResponse.js
  src/js/responses/isochroneResponse.js
  src/js/responses/nearestResponse.js
  src/js/responses/response.js
  src/js/responses/routeResponse.js
  src/js/service/main.js
  src/js/service/service.js
  src/js/service/serviceAdministered.js
  src/js/service/serviceInsider.js
  src/js/service/serviceManager.js
  src/js/service/serviceProcess.js
  src/js/sources/source.js
  src/js/sources/sourceManager.js
  test/functional/request/cucumber/features/support/world.js
  test/integration/mocha/requests/integrationHealthRequest.js
  test/integration/mocha/responses/integrationHealthResponse.js
  test/unit/mocha/requests/testsRequest.js
  test/unit/mocha/responses/testsResponse.js
Labels: enhancement

#46 Feature/add services route
  changelog.md
  documentation/apis/administration/1.0.0/api.yaml
  src/js/administrator/administrator.js
  src/js/apis/admin/1.0.0/index.js
  test/functional/request/cucumber/configurations/local-admin.json
  test/functional/request/cucumber/features/req-admin-1.0.0.feature
Labels: enhancement

#48 [del] onStart option and feature
  changelog.md
  docker/config/road2.json
  documentation/apis/administration/1.0.0/api.yaml
  documentation/configuration/administration/admin_model.yaml
  documentation/developers/concepts.md
  src/js/administrator/administrator.js
  src/js/road2.js
  test/integration/mocha/config/road2.json
Labels: refactor

#47 feat(init): no stop of service if source or resource dir is empty
  changelog.md
  documentation/developers/concepts.md
  src/js/resources/resourceManager.js
  src/js/sources/sourceManager.js
  test/functional/configuration/cucumber/features/conf-service.feature
  test/functional/configuration/cucumber/features/support/steps.js
  test/functional/configuration/cucumber/features/support/world.js
Labels: enhancement

#51 [feat] init admin without services
  changelog.md
  documentation/developers/concepts.md
  package.json
  src/js/administrator/administrator.js
  src/js/road2.js
Labels: enhancement

#58 [fix] pgrouting sources without attributes
  documentation/apis/administration/1.0.0/api.yaml
  documentation/configuration/resources/pgr.resource
  documentation/configuration/resources/smartpgr.resource
  documentation/configuration/sources/pgr.source
  src/js/sources/pgrSource.js
  test/functional/request/cucumber/features/req-simple-1.0.0-pgr.feature
Labels: bug

#59 [feat] compute GET /configuration
  changelog.md
  src/js/administrator/administrator.js
  src/js/apis/admin/1.0.0/index.js
  test/functional/request/cucumber/configurations/local-admin.json
  test/functional/request/cucumber/features/req-admin-1.0.0.feature
Labels: enhancement

#60 feat(test web): add definition of user resource for isochrone
  test/www/isochrone.html
  test/www/js/isochrone.js
Labels: enhancement, test
